schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.warrior.stg.well-played.gg/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
